//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eco
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEventSet
    {
        public int fEventId { get; set; }
        public string fUserId { get; set; }
        public string fEventTitle { get; set; }
        public string fCategory { get; set; }
        public string fEventFromDay { get; set; }
        public string fEventFromTime { get; set; }
        public string fEventEndDate { get; set; }
        public string fEventEndTime { get; set; }
        public string fEventImgPath { get; set; }
        public string fEventLocation { get; set; }
        public string fEventDescription { get; set; }
        public Nullable<int> fEventFeeOrFree { get; set; }
        public Nullable<int> fEventFee { get; set; }
        public string fEventFromDay_R { get; set; }
        public string fEventFromTime_R { get; set; }
        public string fEventEndDate_R { get; set; }
        public string fEventEndTime_R { get; set; }
        public string fRemark { get; set; }
        public Nullable<int> ferUserId { get; set; }
        public Nullable<int> fnumAttendPeople { get; set; }
        public Nullable<int> ferName { get; set; }
        public Nullable<int> ferPhone { get; set; }
        public Nullable<int> ferEmail { get; set; }
        public Nullable<int> ferGender { get; set; }
        public Nullable<int> ferBirthday { get; set; }
        public Nullable<int> ferIdentity { get; set; }
        public Nullable<int> ferOccupation { get; set; }
        public Nullable<int> ferVeganOrNot { get; set; }
        public string ferOtherColumn1 { get; set; }
        public string ferOtherColumn2 { get; set; }
        public string ferOtherColumn3 { get; set; }
        public string ferOtherColumn4 { get; set; }
        public string ferOtherColumn5 { get; set; }
    }
}
